# Generated by Django 2.2.19 on 2022-12-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_auto_20221216_1343"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
