# Generated by Django 2.2.19 on 2023-02-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.CharField(
                help_text="Текст комментария",
                max_length=300,
                verbose_name="Текст",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
    ]
