# Generated by Django 2.2.19 on 2023-02-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0011_follow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="authot",
            new_name="author",
        ),
    ]
