# Generated by Django 2.2.19 on 2023-02-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0013_auto_20230202_1531"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(
                help_text="Текст комментария",
                max_length=300,
                verbose_name="Текст",
            ),
        ),
    ]
