# Generated by Django 2.2.19 on 2023-02-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0014_auto_20230203_1310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
