# Generated by Django 2.2.19 on 2023-02-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0018_auto_20230207_1435"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together=set(),
        ),
    ]
